name: lilliserver

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_TUNNEL_JSON_B64: ${{ secrets.CLOUDFLARE_TUNNEL_JSON_B64 }}
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Nextcloud AIO
        run: |
          sudo docker run -d \
            --init \
            --sig-proxy=false \
            --name nextcloud-aio-mastercontainer \
            --restart always \
            --publish 80:80 \
            --publish 8080:8080 \
            --publish 8443:8443 \
            --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
            --volume /var/run/docker.sock:/var/run/docker.sock:ro \
            ghcr.io/nextcloud-releases/all-in-one:latest

      - name: Check running containers
        run: docker ps -a

      - name: Check listening ports
        run: |
          sudo ss -tlnp
          sudo sh -c 'echo "0 2147483647" > /proc/sys/net/ipv4/ping_group_range'
          curl -v http://0.0.0.0:8443
              
      - name: Install Cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb
    
      - name: Run Cloudflare Tunnel
        run: cloudflared tunnel --no-tls-verify --url https://0.0.0.0:8443

