name: lilliserver

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Nextcloud AIO
        run: |
          sudo docker run -d \
            --init \
            --sig-proxy=false \
            --name nextcloud-aio-mastercontainer \
            --restart always \
            --publish 80:80 \
            --publish 8080:8080 \
            --publish 8443:8443 \
            --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
            --volume /var/run/docker.sock:/var/run/docker.sock:ro \
            ghcr.io/nextcloud-releases/all-in-one:latest
      - name: Run Cloudflare Tunnel
        run: |
          mkdir -p ~/.cloudflared
          echo "${{ secrets.CLOUDFLARE_TUNNEL_JSON_B64 }}" | base64 -d > ~/.cloudflared/tunnel.json
      
          cat > ~/.cloudflared/config.yml <<'EOL'
        tunnel: cl-lilli
        credentials-file: /home/runner/.cloudflared/tunnel.json
        
        ingress:
          - hostname: cloud.lilli.eu.org
            service: http://localhost:8080
          - service: http_status:404
EOL

            cloudflared tunnel run cl-lilli
